### ISSUE TITLE
Bug: Won't Compact

### ISSUE THREAD

**Issue by AlphaLeoli** [ebicep/ChatPlus#34] opened 2024-09-16 19:14 UTC
Minecraft: 1.21.1
Mod: 2.0.2

Chat just won't compact messages. It looks like this
![image](https://github.com/user-attachments/assets/1d89f8f0-a5c5-45b0-b1ab-5788de10e633)

And these are my settings
![image](https://github.com/user-attachments/assets/a833cc94-f194-44f1-b376-9b0f7c6ea908)

I've actually had this problem with other compactor mods, if that helps at all. The only compactor mod that's really worked for me is the one in [Chat Tools](https://modrinth.com/mod/chat-tools)

**Comment by AlphaLeoli** [comment] 2024-09-16 19:16
![image](https://github.com/user-attachments/assets/631e738c-7b51-44e9-9c9f-b271ef8fba77)
Also they randomly uncompact when I change settings. In this example, I changed the background color of the chat tab

**Comment by AlphaLeoli** [comment] 2024-09-16 19:32
![image](https://github.com/user-attachments/assets/bcd02348-3f16-492d-a318-4b2dd3a0f1c7)
resets every second

**Comment by ebicep** [comment] 2024-09-16 20:38
It is working as intended if you have timestamps enabled. If you hover over your message it shows the timestamp of the message, every second the timestamp changes (assuming you have seconds on) which means it is a new message. You can ignore the timestamps when compacting the messages by enabling the "Ignore Timestamps" option.

As for the uncompacting, I will look into it.

**Comment by ebicep** [comment] 2024-09-25 01:55
Fixed in v2.1.0

**Closed as completed by ebicep** 2024-09-25 01:55 UTC
