### ISSUE TITLE
Having an issue with Hover-over rendering.

### ISSUE THREAD

**Issue by LemonBeee** [ebicep/ChatPlus#33] opened 2024-09-16 12:06 UTC
![javaw_QSqeBFgw7F](https://github.com/user-attachments/assets/96aa9787-6495-466f-8a21-725337f8f8f2)
I'm playing on a vanilla server that utilizes hover-over mechanics in chat for showcasing and similar scenarios.

However, anything rendered in chat, will be *below* the chatbox when Chat Plus is enabled, is there anything I can do to make hover-over boxes render over chat plus?

**Comment by LemonBeee** [comment] 2024-09-16 12:07
The same happens with tabbing, like with playernames
![javaw_MxR4Tli1QW](https://github.com/user-attachments/assets/25d9065b-4d7b-4b5c-8a8b-834c12f41bea)

**Comment by ebicep** [comment] 2024-09-16 12:10
Are you using v2.0.1+

**Comment by LemonBeee** [comment] 2024-09-16 12:14
Ahhh didn't realize there was a new version, modrinth didn't let me update past 2.0.0 That's me being silly e-e

Lemme see if everything works :)

**Comment by LemonBeee** [comment] 2024-09-16 12:16
yeah, still having the same issue. Running 2.0.2 now
![javaw_ldOk4f6Vnb](https://github.com/user-attachments/assets/459b8fbc-5531-41e2-8148-5070290b6057)

**Comment by ebicep** [comment] 2024-09-18 02:31
Unable to reproduce, are you sure you are using the latest version?
If so, do you still have this problem just using ChatPlus + on other servers?
![image](https://github.com/user-attachments/assets/6dba7edd-8eba-4364-a307-7270ce267f49)

**Comment by walkersgaming** [comment] 2024-09-19 11:00
![image](https://github.com/user-attachments/assets/e3c02f97-67e6-4d7e-bae1-1783f6eddb4a)
![image](https://github.com/user-attachments/assets/46d7e632-c72c-443c-a973-15b9a844f2dd)

I also have the same two issues, using 2.0.2 Fabric and with multiple chat windows/tabs created

**Comment by ebicep** [comment] 2024-09-25 01:55
Fixed in v2.1.0

**Closed as completed by ebicep** 2024-09-25 01:55 UTC
